/*
 * Automatically generated by jrpcgen 1.0.7 on 1/4/15 12:29 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package client.mount;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class fhandle implements XdrAble {

    public byte [] value;

    public fhandle() {
    }

    public fhandle(byte [] value) {
        this.value = value;
    }

    public fhandle(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeOpaque(value, mount.FHSIZE);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeOpaque(mount.FHSIZE);
    }

}
// End of fhandle.java
