/*
 * Automatically generated by jrpcgen 1.0.7 on 1/4/15 12:29 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package client.mount;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class MountList implements XdrAble {
    public Name hostname;
    public DirPath directory;
    public MountList nextentry;

    public MountList() {
    }

    public MountList(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        hostname.xdrEncode(xdr);
        directory.xdrEncode(xdr);
        nextentry.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        hostname = new Name(xdr);
        directory = new DirPath(xdr);
        nextentry = new MountList(xdr);
    }

}
// End of mountlist.java
